# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleship.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61ttleship.proto\x12\nbattleship\"\x1f\n\x03Hit\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"q\n\x07Request\x12\r\n\x05token\x18\x01 \x01(\x05\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.battleship.RqType\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x12\x1e\n\x03hit\x18\x04 \x01(\x0b\x32\x0f.battleship.HitH\x00\x42\x05\n\x03req\"r\n\x08Response\x12\r\n\x05token\x18\x01 \x01(\x05\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.battleship.RsType\x12\x0e\n\x04miss\x18\x03 \x01(\x08H\x00\x12\x1e\n\x03hit\x18\x04 \x01(\x0b\x32\x0f.battleship.HitH\x00\x42\x05\n\x03res*4\n\x06RqType\x12\x0f\n\x0bRQ_REGISTER\x10\x00\x12\r\n\tRQ_UPDATE\x10\x01\x12\n\n\x06RQ_HIT\x10\x02*S\n\x06RsType\x12\n\n\x06RS_HIT\x10\x00\x12\x16\n\x12RS_LAST_HIT_UPDATE\x10\x01\x12\x0f\n\x0bRS_GAME_END\x10\x02\x12\x14\n\x10RS_INVALID_VALUE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battleship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RQTYPE']._serialized_start=296
  _globals['_RQTYPE']._serialized_end=348
  _globals['_RSTYPE']._serialized_start=350
  _globals['_RSTYPE']._serialized_end=433
  _globals['_HIT']._serialized_start=32
  _globals['_HIT']._serialized_end=63
  _globals['_REQUEST']._serialized_start=65
  _globals['_REQUEST']._serialized_end=178
  _globals['_RESPONSE']._serialized_start=180
  _globals['_RESPONSE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
